import { FlowchartEdge, FlowchartNode } from '../types/flowchart';

export interface FlowchartTemplate {
  id: string;
  titleKey: 'templateAuth' | 'templateOrder' | 'templateSupport' | 'templateData';
  descKey: 'templateAuthDesc' | 'templateOrderDesc' | 'templateSupportDesc' | 'templateDataDesc';
  nodes: FlowchartNode[];
  edges: FlowchartEdge[];
}

export const TEMPLATES: FlowchartTemplate[] = [
  {
    id: 'user-auth',
    titleKey: 'templateAuth',
    descKey: 'templateAuthDesc',
    nodes: [
      {
        id: 'node-start',
        type: 'terminal',
        x: 320,
        y: 40,
        width: 160,
        height: 54,
        label: 'ورود کاربر / Start Login',
        fill: '#EFF6FF',
        stroke: '#3B82F6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#1E3A8A',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'node-input',
        type: 'input-output',
        x: 310,
        y: 130,
        width: 180,
        height: 60,
        label: 'دریافت ایمیل و رمز عبور',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'node-dec-cred',
        type: 'decision',
        x: 300,
        y: 230,
        width: 200,
        height: 80,
        label: 'اعتبار اطلاعات صحیح است؟',
        fill: '#FEF3C7',
        stroke: '#F59E0B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#78350F',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'node-err',
        type: 'process',
        x: 580,
        y: 242,
        width: 160,
        height: 56,
        label: 'نمایش خطای نام کاربری',
        fill: '#FFF1F2',
        stroke: '#F43F5E',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#881337',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'node-sub-2fa',
        type: 'subroutine',
        x: 310,
        y: 350,
        width: 180,
        height: 60,
        label: 'سرویس پیامک تأیید دو مرحله‌ای',
        fill: '#ECFEFF',
        stroke: '#06B6D4',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#164E63',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'node-dec-otp',
        type: 'decision',
        x: 300,
        y: 450,
        width: 200,
        height: 80,
        label: 'کد پیامک معتبر است؟',
        fill: '#FEF3C7',
        stroke: '#F59E0B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#78350F',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'node-db',
        type: 'database',
        x: 315,
        y: 570,
        width: 170,
        height: 64,
        label: 'ثبت سشن در دیتابیس',
        fill: '#F5F3FF',
        stroke: '#8B5CF6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#4C1D95',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'node-end',
        type: 'terminal',
        x: 320,
        y: 670,
        width: 160,
        height: 54,
        label: 'هدایت به داشبورد اصلی',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'node-note',
        type: 'note',
        x: 60,
        y: 220,
        width: 170,
        height: 80,
        label: 'توجه: بعد از ۵ تلاش ناموفق حساب برای ۱۵ دقیقه قفل می‌شود.',
        fill: '#FEFCE8',
        stroke: '#EAB308',
        strokeWidth: 1.5,
        strokeStyle: 'dashed',
        textColor: '#713F12',
        fontSize: 12,
        fontWeight: 'normal',
        textAlign: 'left',
      },
    ],
    edges: [
      {
        id: 'e1',
        sourceNodeId: 'node-start',
        sourcePort: 'bottom',
        targetNodeId: 'node-input',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e2',
        sourceNodeId: 'node-input',
        sourcePort: 'bottom',
        targetNodeId: 'node-dec-cred',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e3',
        sourceNodeId: 'node-dec-cred',
        sourcePort: 'right',
        targetNodeId: 'node-err',
        targetPort: 'left',
        lineType: 'orthogonal',
        label: 'خیر (No)',
        color: '#F43F5E',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e4',
        sourceNodeId: 'node-err',
        sourcePort: 'top',
        targetNodeId: 'node-input',
        targetPort: 'right',
        lineType: 'orthogonal',
        label: 'تلاش مجدد',
        color: '#F43F5E',
        strokeWidth: 2,
        style: 'dashed',
        arrowEnd: true,
      },
      {
        id: 'e5',
        sourceNodeId: 'node-dec-cred',
        sourcePort: 'bottom',
        targetNodeId: 'node-sub-2fa',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'بله (Yes)',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e6',
        sourceNodeId: 'node-sub-2fa',
        sourcePort: 'bottom',
        targetNodeId: 'node-dec-otp',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e7',
        sourceNodeId: 'node-dec-otp',
        sourcePort: 'bottom',
        targetNodeId: 'node-db',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'تأیید شد',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'e8',
        sourceNodeId: 'node-db',
        sourcePort: 'bottom',
        targetNodeId: 'node-end',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
    ],
  },
  {
    id: 'order-process',
    titleKey: 'templateOrder',
    descKey: 'templateOrderDesc',
    nodes: [
      {
        id: 'ord-start',
        type: 'terminal',
        x: 320,
        y: 40,
        width: 170,
        height: 52,
        label: 'ثبت سفارش مشتری',
        fill: '#EFF6FF',
        stroke: '#3B82F6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#1E3A8A',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'ord-check',
        type: 'decision',
        x: 300,
        y: 130,
        width: 210,
        height: 80,
        label: 'موجودی انبار کافی است؟',
        fill: '#FEF3C7',
        stroke: '#F59E0B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#78350F',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'ord-notify-oos',
        type: 'process',
        x: 580,
        y: 142,
        width: 160,
        height: 56,
        label: 'اطلاع عدم موجودی کالا',
        fill: '#FFF1F2',
        stroke: '#F43F5E',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#881337',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'ord-pay',
        type: 'subroutine',
        x: 315,
        y: 250,
        width: 180,
        height: 60,
        label: 'انتقال به درگاه بانکی شاپرک',
        fill: '#ECFEFF',
        stroke: '#06B6D4',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#164E63',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'ord-pay-dec',
        type: 'decision',
        x: 300,
        y: 350,
        width: 210,
        height: 80,
        label: 'تراکنش پرداخت موفق بود؟',
        fill: '#FEF3C7',
        stroke: '#F59E0B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#78350F',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'ord-doc',
        type: 'document',
        x: 315,
        y: 470,
        width: 180,
        height: 70,
        label: 'صدور فاکتور رسمی PDF',
        fill: '#F5F3FF',
        stroke: '#8B5CF6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#4C1D95',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'ord-pack',
        type: 'process',
        x: 315,
        y: 580,
        width: 180,
        height: 56,
        label: 'بسته‌بندی و تحویل به پست',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'ord-end',
        type: 'terminal',
        x: 320,
        y: 675,
        width: 170,
        height: 52,
        label: 'تکمیل سفارش و رهگیری',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    ],
    edges: [
      {
        id: 'oe1',
        sourceNodeId: 'ord-start',
        sourcePort: 'bottom',
        targetNodeId: 'ord-check',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe2',
        sourceNodeId: 'ord-check',
        sourcePort: 'right',
        targetNodeId: 'ord-notify-oos',
        targetPort: 'left',
        lineType: 'orthogonal',
        label: 'خیر',
        color: '#F43F5E',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe3',
        sourceNodeId: 'ord-check',
        sourcePort: 'bottom',
        targetNodeId: 'ord-pay',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'بله',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe4',
        sourceNodeId: 'ord-pay',
        sourcePort: 'bottom',
        targetNodeId: 'ord-pay-dec',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe5',
        sourceNodeId: 'ord-pay-dec',
        sourcePort: 'bottom',
        targetNodeId: 'ord-doc',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'موفق',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe6',
        sourceNodeId: 'ord-doc',
        sourcePort: 'bottom',
        targetNodeId: 'ord-pack',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'oe7',
        sourceNodeId: 'ord-pack',
        sourcePort: 'bottom',
        targetNodeId: 'ord-end',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
    ],
  },
  {
    id: 'support-escalation',
    titleKey: 'templateSupport',
    descKey: 'templateSupportDesc',
    nodes: [
      {
        id: 'sup-1',
        type: 'terminal',
        x: 320,
        y: 40,
        width: 170,
        height: 52,
        label: 'دریافت تیکت مشتری',
        fill: '#EFF6FF',
        stroke: '#3B82F6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#1E3A8A',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'sup-2',
        type: 'process',
        x: 315,
        y: 130,
        width: 180,
        height: 56,
        label: 'دسته‌بندی خودکار با هوش مصنوعی',
        fill: '#F5F3FF',
        stroke: '#8B5CF6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#4C1D95',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'sup-3',
        type: 'decision',
        x: 300,
        y: 226,
        width: 210,
        height: 80,
        label: 'اولویت بحرانی (P1/P2) است؟',
        fill: '#FEF3C7',
        stroke: '#F59E0B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#78350F',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'sup-4-low',
        type: 'process',
        x: 100,
        y: 340,
        width: 170,
        height: 56,
        label: 'پاسخ توسط ربات پشتیبان',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'sup-4-high',
        type: 'process',
        x: 540,
        y: 340,
        width: 180,
        height: 56,
        label: 'هشدار فوری به کشیک فنی',
        fill: '#FFF1F2',
        stroke: '#F43F5E',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#881337',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'sup-5',
        type: 'terminal',
        x: 320,
        y: 460,
        width: 170,
        height: 52,
        label: 'حل تیکت و نظرسنجی رضایت',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    ],
    edges: [
      {
        id: 'se1',
        sourceNodeId: 'sup-1',
        sourcePort: 'bottom',
        targetNodeId: 'sup-2',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'se2',
        sourceNodeId: 'sup-2',
        sourcePort: 'bottom',
        targetNodeId: 'sup-3',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'se3',
        sourceNodeId: 'sup-3',
        sourcePort: 'left',
        targetNodeId: 'sup-4-low',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'عادی',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'se4',
        sourceNodeId: 'sup-3',
        sourcePort: 'right',
        targetNodeId: 'sup-4-high',
        targetPort: 'top',
        lineType: 'orthogonal',
        label: 'بحرانی',
        color: '#F43F5E',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'se5',
        sourceNodeId: 'sup-4-low',
        sourcePort: 'bottom',
        targetNodeId: 'sup-5',
        targetPort: 'left',
        lineType: 'orthogonal',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'se6',
        sourceNodeId: 'sup-4-high',
        sourcePort: 'bottom',
        targetNodeId: 'sup-5',
        targetPort: 'right',
        lineType: 'orthogonal',
        color: '#F43F5E',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
    ],
  },
  {
    id: 'data-pipeline',
    titleKey: 'templateData',
    descKey: 'templateDataDesc',
    nodes: [
      {
        id: 'dp-1',
        type: 'terminal',
        x: 320,
        y: 40,
        width: 170,
        height: 52,
        label: 'آغاز واکشی رویدادها',
        fill: '#EFF6FF',
        stroke: '#3B82F6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#1E3A8A',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'dp-2',
        type: 'input-output',
        x: 310,
        y: 130,
        width: 190,
        height: 58,
        label: 'دریافت استریم از وب‌هوک',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'dp-3',
        type: 'process',
        x: 315,
        y: 226,
        width: 180,
        height: 56,
        label: 'اعتبارسنجی اسکیمای JSON',
        fill: '#F8FAFC',
        stroke: '#64748B',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#0F172A',
        fontSize: 13,
        fontWeight: 'normal',
        textAlign: 'center',
      },
      {
        id: 'dp-4',
        type: 'database',
        x: 320,
        y: 320,
        width: 170,
        height: 64,
        label: 'ذخیره در پایگاه داده',
        fill: '#F5F3FF',
        stroke: '#8B5CF6',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#4C1D95',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
      {
        id: 'dp-5',
        type: 'terminal',
        x: 320,
        y: 420,
        width: 170,
        height: 52,
        label: 'انتشار رویداد به داشبورد',
        fill: '#F0FDF4',
        stroke: '#10B981',
        strokeWidth: 2,
        strokeStyle: 'solid',
        textColor: '#064E3B',
        fontSize: 13,
        fontWeight: 'bold',
        textAlign: 'center',
      },
    ],
    edges: [
      {
        id: 'de1',
        sourceNodeId: 'dp-1',
        sourcePort: 'bottom',
        targetNodeId: 'dp-2',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'de2',
        sourceNodeId: 'dp-2',
        sourcePort: 'bottom',
        targetNodeId: 'dp-3',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'de3',
        sourceNodeId: 'dp-3',
        sourcePort: 'bottom',
        targetNodeId: 'dp-4',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#64748B',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
      {
        id: 'de4',
        sourceNodeId: 'dp-4',
        sourcePort: 'bottom',
        targetNodeId: 'dp-5',
        targetPort: 'top',
        lineType: 'orthogonal',
        color: '#10B981',
        strokeWidth: 2,
        style: 'solid',
        arrowEnd: true,
      },
    ],
  },
];
